{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
data:
  {{- range .Values.configMap.values }}
  "{{.name}}": "{{.value}}"
  {{end}}
{{- end }}